spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/558

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    sql: debug
